robotology/osqp-eigen

.gitignore
CMakeLists.txt
include/OptimizerData.tpp
include/OptimizerSolver.hpp
include/OptimizerSolver.tpp
include/SparseMatrixHelper.hpp
include/SparseMatrixHelper.tpp
src/OptimizerData.cpp
src/OptimizerSolver.cpp
tests/SparseMatrixTest.cpp

The aim was to reduce the usage of Eigen methods like ``makeCompressed`` and the usage of dynamic memory allocation.
Solved a couple of bugs in the process (wrong updates of matrices, memory leaks in destructor).

Various fixes

---

.travis.yml

This fixes `travis` script by handling the new installation procedure of `osqp`+`qldld.`

Update travis script to handle new installation procedure of osqp

---

include/OsqpEigen/Solver.hpp
src/Solver.cpp

Sorry for being late.
This PR is related to #21

Add new api: getDualSolution

---

CMakeLists.txt
include/OsqpEigen/Solver.hpp
include/OsqpEigen/Solver.tpp
src/Solver.cpp

**The use of raw pointers is error-prone, makes the code unclear, and it is a cause of my headache.**   
Furthermore, in our specific case, using a raw pointer for `OSQPWorkspace` imposes us to implement a custom deleter (i.e. bye bye [Rule of zero](https://en.cppreference.com/w/cpp/language/rule_of_three)).
Breaking the **rule of zero** may bring to undesired behaviors (i.e. the move assignment/constructor operator are implicitly deleted  #37)
For the aforementioned problems, I decided to work on this PR. 
The `OSQPWorkspace` struct is now stored in an `unique_ptr`. However, deleting a `OSQPWorkspace` instance is not trivial. Indeed the [`osqp_clean()`](https://osqp.org/docs/interfaces/cc++#_CPPv412osqp_cleanupP13OSQPWorkspace) function has to be called. For this reason, I implemented a …

Use unique_ptr instead of raw pointer for OSQPWorkspace

---

tests/MPCTest.cpp
tests/MPCUpdateMatricesTest.cpp
tests/QPTest.cpp

Fixes #55 
I got this fix from https://github.com/monero-project/monero/pull/6346/files

Using nullptr to avoid static assert on test names.

---

CMakeLists.txt
include/OsqpEigen/Settings.hpp
src/Settings.cpp

As it can be noticed from the [``osqp`` code](https://github.com/oxfordcontrol/osqp/blob/6fb6db97a33a81d40a006ffc8a4213d7599bb656/include/types.h#L125-L176) some settings may not be available depending on the specific Cmake settings. With this PR we copy the same checks adding an error message in case some settings are not available. 
I also added the ``time_limit`` setting (see https://github.com/robotology/osqp-eigen/issues/38).
~In draft since I have to bump the version number, but there are other PR open at the moment.~

Check that all the settings are actually available.

---

CMakeLists.txt
include/OsqpEigen/Solver.tpp

I noticed that there are cases in which the solver initialization while updating the hessian and the constraint matrices throw an error. I.e. The new hessian matrix is not SDP. In case of problems, without checking the return value of `initSolver()`, the code crashes with segmentation fault in `setPrimalVariable()`.
This PR fixes the aforementioned problem.

Check the initialization of the solver went fine while updating hessian and constraint matrix

---

include/OsqpEigen/Solver.hpp
src/Solver.cpp

This is useful so I can do things like this.
```
if (solver_.workspace()->info->status_val == -3)
{
// Print debugging info
Eigen::Map<Eigen::VectorXd> primal_certificate(solver_.workspace()->delta_x, num_cnts_, 1);
}
```

Expose OSQP Workspace

---

.github/workflows/gh-pages.yml

This new release addresses https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

GitHub Action: Bump the webfactory/ssh-agent to v0.4.1

---

CMakeLists.txt
include/OsqpEigen/Data.tpp
include/OsqpEigen/Debug.hpp
include/OsqpEigen/Solver.tpp
include/OsqpEigen/SparseMatrixHelper.tpp
src/Data.cpp
src/Debug.cpp
src/Settings.cpp
src/Solver.cpp

Add option for enabling/disabling debug error output to cerr

---

CMakeLists.txt

The ``cxx_std_14`` feature has been added starting from the 3.8 version. See https://cmake.org/cmake/help/v3.8/prop_gbl/CMAKE_CXX_KNOWN_FEATURES.html#prop_gbl:CMAKE_CXX_KNOWN_FEATURES vs https://cmake.org/cmake/help/v3.5/prop_gbl/CMAKE_CXX_KNOWN_FEATURES.html#prop_gbl:CMAKE_CXX_KNOWN_FEATURES

Bump the required CMake version

---

CMakeLists.txt
include/OsqpEigen/Constants.hpp
include/OsqpEigen/Solver.hpp
src/Solver.cpp

This PR introduces `Status` and `ErrorExitFlag` enum class that replicates the content of https://osqp.org/docs/interfaces/status_values.html
Furthermore, I implemented:
1. `OsqpEigen::Solver::solveProblem`: this function will substitute `OsqpEigen::Solver::solve` and it will return the `ErrorExitFlag`
2. `OsqpEigen::Solver::getStatus` to get the internal state of `osqp` solver. 
This closes #110

Handle osqp errors

---

cmake/AddUninstallTarget.cmake

From https://github.com/robotology/ycm/blob/v0.14.1/modules/AddUninstallTarget.cmake
The osqp-eigen PR https://github.com/robotology/osqp-eigen/pull/117 introduced a ninja-related regression as it ported from YCM the PR https://github.com/robotology/ycm/issues/169  without porting the related commit https://github.com/robotology/ycm/commit/f2c61b1b9f5b2a7935bf79d1d43a68a218225804 that is a fix for https://github.com/robotology/ycm/issues/240 . To avoid the problem, I just import the module from the latest YCM release.
Fix https://github.com/robotology/robotology-superbuild/issues/1153 .

Import AddUninstallTarget.cmake from YCM v0.14.1 to fix compilation with ninja

---

include/OsqpEigen/Solver.hpp
src/Solver.cpp

Resolves compilation error when c_float is set to float.

Resolved Compilation error when using float

---

.github/workflows/ci.yml

Fix https://github.com/robotology/osqp-eigen/issues/132 .

Update catch2 to v2.13.9 and osqp to v0.6.3 in CI

---

include/OsqpEigen/SparseMatrixHelper.tpp

I made a small fix for a missing include when compiling with MSVC 2022 (at line 56 there is `assert(innerOsqpPosition == numberOfNonZeroCoeff);` which requires `<cassert>` header).

Missing include when compiling with MSVC 2022

---

CMakeLists.txt
cmake/OsqpEigenDependencies.cmake
cmake/try-osqp.cpp
include/OsqpEigen/Compat.hpp
include/OsqpEigen/Constants.hpp
include/OsqpEigen/Solver.hpp
include/OsqpEigen/Solver.tpp
include/OsqpEigen/SparseMatrixHelper.hpp
src/Data.cpp
src/Settings.cpp
src/Solver.cpp

This PR updates osqp-eigen to be compatible with OSQP v1.0.0 (currently in beta). I have kept the API of osqp-eigen (almost) identical
The following things are known to not work (and afaik cannot be done with OSQP v1.0.0)
- `bool OsqpEigen::Solver::getPrimalVariable(Eigen::Matrix<T, n, 1> &dualVariable)` and `bool OsqpEigen::Solver::getDualVariable(Eigen::Matrix<T, m, 1> &dualVariable)` return the solution held in the solution rather than the values in the workspace (which are not accessible anymore)
- `bool OsqpEigen::Solver::clearSolverVariables()` is a no-op since workspace is opaque now
Otherwise I can at least confirm the unit tests pass but I haven't tried much more.

Make the code compatible with OSQP v1.0.0

---

cmake/OsqpEigenDependencies.cmake

In some corner cases (see https://github.com/robotology/robotology-superbuild/issues/1451) `try_compile`  is creating problems, so it is convenient not to call it at all by setting `OSQP_IS_V1` as a CMake option if the OSQP version used is known.
fyi @gergondet

Do not run try_compile if OSQP_IS_V1 is already defined

---

include/OsqpEigen/Compat.hpp
include/OsqpEigen/SparseMatrixHelper.tpp
src/Data.cpp
tests/SparseMatrixTest.cpp

Fix https://github.com/robotology/osqp-eigen/issues/146, this should reduce new issue open in the repo.
fyi @gergondet

Fix compatibility of OSQP 1 when using Windows

---

tests/QPTest.cpp

This was a bit hidden by https://github.com/robotology/osqp-eigen/issues/161, but I recently noticed that while most time the test `QPUnitTests` the output was:
~~~
traversaro@IITBMP014LW012:~/robotology-superbuild/buildapt/src/OsqpEigen$ ctest -VV -R QPUnitTest
UpdateCTestConfiguration  from :/home/traversaro/robotology-superbuild/buildapt/src/OsqpEigen/DartConfiguration.tcl
Parse Config file:/home/traversaro/robotology-superbuild/buildapt/src/OsqpEigen/DartConfiguration.tcl
UpdateCTestConfiguration  from :/home/traversaro/robotology-superbuild/buildapt/src/OsqpEigen/DartConfiguration.tcl
Parse Config file:/home/traversaro/robotology-superbuild/buildapt/src/OsqpEigen/DartConfiguration.tcl
Test project /home/traversaro/robotology-superbuild/buildapt/src/OsqpEigen
Constructing a list of …

Avoid non-deterministic QPUnitTests failure by setting `polish` to true in QPUnitTests

---

.github/workflows/ci.yml
.github/workflows/test-pixi.yaml
.github/workflows/update-pixi-lockfile.yaml
.gitignore
cmake/AddOsqpEigenUnitTest.cmake
cmake/Catch2Main.cpp.in
cmake/OsqpEigenDependencies.cmake
pixi.lock
pixi.toml
tests/MPCTest.cpp
tests/MPCUpdateMatricesTest.cpp
tests/QPTest.cpp
tests/SparseMatrixTest.cpp
tests/UpdateMatricesTest.cpp

* Migrate from catch2 2.* to 3.* (similar to https://github.com/ami-iit/matio-cpp/pull/56)
* Drop homebrew CI (fix https://github.com/robotology/osqp-eigen/issues/161)
* Add job on macOS, Windows and Linux that runs tests with conda-forge dependencies using pixi.
The main advantage of pixi that to replicate the tests on your machine you just need to run:
~~~
git clone https://github.com/robotology/osqp-eigen/
cd osqp-eigen
pixi run test
~~~

General CI cleanup November 2024

---

.github/workflows/ci.yml
CMakeLists.txt
cmake/OsqpEigenDependencies.cmake
cmake/try-osqp-v1-final.cpp
cmake/try-osqp-v1.cpp
docs/Doxyfile
include/OsqpEigen/Compat.hpp
package.xml

For avoiding problems in the transition from osqp v0.6.3 to v1.0.0, I would like to make a osqp-eigen release that is compatible with all recent osqp versions. Once that is done, we can drop 0.6.3 support.
Fix https://github.com/robotology/osqp-eigen/issues/188 .
Fix https://github.com/robotology/osqp-eigen/pull/186 .

Support building v0.6.3, v1.0.0.beta1 and v1.0.0 and bump version to 0.10.0

---

include/OsqpEigen/Constants.hpp

In osqp 0.6, the `OSQP_TIME_LIMIT_REACHED` macro is only defined if the `PROFILING` macro is defined by the osqp configuration, see https://github.com/osqp/osqp/blob/v0.6.3/include/constants.h#L25-L27, and so also `OsqpEigen::Status::TimeLimitReached` is only defined if `PROFILING` is defined. 
From osqp 1.0.0beta0 instead, the `OSQP_TIME_LIMIT_REACHED` macro is always defined, see https://github.com/osqp/osqp/blob/v1.0.0.beta0/include/public/osqp_api_constants.h#L36 .
This PR ensures that when using osqp 1.0.0beta0 or later, the `OsqpEigen::Status::TimeLimitReached` is always defined, fixing downstream errors such as https://github.com/conda-forge/qpsolvers-eigen-feedstock/pull/5#issuecomment-2781403658 .

Fix definition of OsqpEigen::Status::TimeLimitReached in osqp >= 1

---

include/OsqpEigen/Settings.hpp
src/Settings.cpp

Add a method to configure the duality gap termination check option added in OSQP v1.0.0.

Add duality gap termination check configuration

---

include/OsqpEigen/Settings.hpp
src/Settings.cpp

Fix https://github.com/robotology/osqp-eigen/issues/213 . All the code was generated in GitHub Copilot with GPT-5 with the prompt:
~~~
Can you please solve this issue: [https://github.com/robotology/osqp-eigen/issues/213](vscode-file://vscode-app/c:/Users/straversaro/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/workbench.html) .
Please make sure:
* That the style of the new setters and getters uses the existing camel case style of C++ methods
* That the project continues to compile on older osqp version in which this settings are not available, using the OSQP_EIGEN_OSQP_IS_V1 and OSQP_EIGEN_OSQP_IS_V1_FINAL macros and appropriate ifdef contions
~~~
and then the correcting prompt:
~~~
Sorry, it seems that I Was wrong, getters are not …

Expose osqp v1.0.0 specific settings
